"""AI integration for command generation with structured output.

Uses LiteLLM as primary backend (100+ providers), with optional google-genai
fallback for Gemini-specific features.
"""

import json
import os
import platform
from pathlib import Path
from typing import Optional

from pydantic import BaseModel

DONE_SENTINEL = "__DONE__"

# Project markers for context-aware detection
PROJECT_MARKERS = {
    "package.json": "Node.js",
    "pyproject.toml": "Python",
    "requirements.txt": "Python",
    "setup.py": "Python",
    "Cargo.toml": "Rust",
    "go.mod": "Go",
    "Makefile": "Make",
    "CMakeLists.txt": "CMake",
    "Dockerfile": "Docker",
    "docker-compose.yml": "Docker Compose",
    "docker-compose.yaml": "Docker Compose",
    ".git": "Git repository",
    "Gemfile": "Ruby",
    "pom.xml": "Java/Maven",
    "build.gradle": "Java/Gradle",
    "tsconfig.json": "TypeScript",
}


# ── Pydantic schemas for structured output ───────────────────────────────────


class CommandResponse(BaseModel):
    """Structured response from the AI for command generation."""
    command: str  # The shell command to execute, or "__DONE__" if objective is complete
    explanation: str  # Brief one-line explanation of what this command does
    is_done: bool  # True if the objective is fully complete


class ExplainResponse(BaseModel):
    """Structured response for command explanation."""
    summary: str  # One-line summary of what the command does
    breakdown: list[str]  # Step-by-step breakdown of each part
    risks: str  # Side effects or risks (empty string if none)


class PlanStep(BaseModel):
    """A single step in an execution plan."""
    step_number: int
    command: str
    explanation: str
    is_reversible: bool
    undo_command: str  # empty string if not reversible


class PlanResponse(BaseModel):
    """Full execution plan generated by AI."""
    summary: str  # one-line plan overview
    steps: list[PlanStep]
    warnings: str  # caveats or empty string


class PlanAdaptResponse(BaseModel):
    """AI response when adapting a plan after failure."""
    assessment: str  # what went wrong
    revised_steps: list[PlanStep]
    should_abort: bool
    abort_reason: str  # empty string if not aborting


class DiagnosisResponse(BaseModel):
    """AI response for diagnosing command failures."""
    root_cause: str       # Plain-English explanation of what went wrong
    fix_command: str      # The command to fix the issue
    explanation: str      # What the fix does
    prevention_tip: str   # How to prevent this in the future
    confidence: str       # "high", "medium", or "low"


class RecipeParameterization(BaseModel):
    """AI response for identifying parameters in a recipe."""
    parameters: list[str]               # e.g. ["project_name", "python_version"]
    parameterized_commands: list[str]    # commands with {{param}} placeholders


class AliasEntry(BaseModel):
    """A single alias suggestion."""
    name: str
    command: str
    reason: str


class AliasSuggestion(BaseModel):
    """AI response for alias suggestions."""
    aliases: list[AliasEntry]


class LessonResponse(BaseModel):
    """AI response for a shell tutorial lesson."""
    explanation: str       # Main lesson content
    examples: list[str]    # Example commands to try
    exercise: str          # A practice exercise
    tips: list[str]        # Helpful tips


class PlaybookGeneration(BaseModel):
    """AI response for generating playbook metadata from a fix session."""
    symptoms: list[str]                  # Observable signs of the problem
    diagnostic_commands: list[str]       # Commands to diagnose the issue
    diagnostic_explanations: list[str]   # What each diagnostic command checks
    what_to_look_for: list[str]          # What to look for in diagnostic output
    prevention_tips: list[str]           # How to prevent this in the future
    category: str                        # "security", "debugging", "system"
    severity: str                        # "critical", "high", "medium", "low"
    tags: list[str]                      # Categorization tags


# ── Shell / environment detection ────────────────────────────────────────────


def _detect_shell_info() -> dict:
    info = {
        "os_name": platform.system(),
        "os_version": platform.version(),
        "cwd": os.getcwd(),
        "home_dir": str(Path.home()),
    }

    if platform.system() == "Windows":
        if os.environ.get("PSModulePath"):
            info["shell"] = "powershell"
        else:
            info["shell"] = "cmd"
    else:
        info["shell"] = os.environ.get("SHELL", "/bin/bash")

    return info


def _detect_project_context() -> str:
    cwd = Path.cwd()
    detected = []
    for marker, label in PROJECT_MARKERS.items():
        if (cwd / marker).exists():
            detected.append(label)
    if not detected:
        return "No specific project type detected."
    return "Detected project types: " + ", ".join(sorted(set(detected)))


# ── Prompts ──────────────────────────────────────────────────────────────────

_ZX_COMMANDS_REFERENCE = """Built-in zx commands (use these instead of shell commands when the request matches):
- zx setup — configure providers, models, budgets
- zx update — self-update package and refresh community index
- zx explain "cmd" — explain a command
- zx history — browse command history
- zx last — show last command
- zx install <url> — install from GitHub/URL
- zx recipe --list/--save/--delete/explore — manage workflow recipes
- zx playbook list/run/share — incident playbooks
- zx undo — undo last plan
- zx fix — diagnose/fix errors
- zx alias suggest/list/add/install — shell alias generator
- zx snapshot take/list/diff/show/delete — context snapshots
- zx learn [topic] — interactive shell tutor
- zx narrate "cmd" — live AI commentary
- zx remote add/remove/list — remote execution via SSH
- zx cost [month] — AI usage costs
- zx budget --show/--monthly/--session — spending limits"""

_ZX_ROUTING_EXAMPLES = """Self-referential routing:
- "update yourself" / "check for updates" → zx update
- "show my budget" / "spending limit" → zx budget --show
- "show costs" / "how much spent" → zx cost
- "save as recipe" → zx recipe --save <name>
- "undo" / "undo last" → zx undo
- "explain <cmd>" → zx explain "<cmd>"
- "show history" → zx history
- "configure" / "setup" → zx setup"""


def _build_system_prompt(shell_info: dict, project_context: str) -> str:
    return f"""You are a command-line assistant that converts natural language into terminal commands.

ENVIRONMENT:
- OS: {shell_info['os_name']} {shell_info['os_version']}
- Shell: {shell_info['shell']}
- CWD: {shell_info['cwd']}
- Home: {shell_info['home_dir']}
- Project: {project_context}

RESPONSE FORMAT:
Return a JSON object: {{"command": "<shell command>", "explanation": "<one-line description>", "is_done": false}}
- "command": exact shell command — no markdown, no backticks, no comments.
- When the objective is FULLY COMPLETE, return: {{"command": "__DONE__", "explanation": "...", "is_done": true}}

COMMAND RULES:
- One logical operation per response. You may chain with `;` for closely related commands (e.g., `cd dir ; ls`). On PowerShell, always use `;` — never `&&`.
- Commands must be valid for {shell_info['shell']}. Use platform-appropriate syntax.
- In multi-step conversations, return only the NEXT command. Analyze prior output to decide.
- If a command fails, try a corrective command. If unrecoverable, return __DONE__.
- Never return destructive commands (rm -rf /, format C:, DROP DATABASE) without explicit user intent.

ZX SELF-AWARENESS:
You are the "zx" CLI. If the request matches a built-in command, return that instead:
{_ZX_COMMANDS_REFERENCE}
{_ZX_ROUTING_EXAMPLES}"""


def _build_plan_prompt(shell_info: dict, project_context: str) -> str:
    return f"""You are a command-line planning assistant. Generate an execution plan for the user's objective.

ENVIRONMENT:
- OS: {shell_info['os_name']} {shell_info['os_version']}
- Shell: {shell_info['shell']}
- CWD: {shell_info['cwd']}
- Home: {shell_info['home_dir']}
- Project: {project_context}

RESPONSE FORMAT:
Return JSON: {{"summary": "<plan overview>", "steps": [...], "warnings": "<caveats or empty>"}}
Each step: {{"step_number": N, "command": "...", "explanation": "...", "is_reversible": bool, "undo_command": "..."}}

INTENT CLASSIFICATION — classify the request, then plan accordingly:

1. INSPECTION / EXPLORATION (user wants to understand something on their system):
   Questions about files, directories, processes, services, logs, or system state.
   These REQUIRE running commands to answer — generate steps to inspect, then summarize findings.
   Examples: "what is this directory about?", "what's running on port 8080?", "what's in this file?", "what is c:\\tmp directory about?"
   IMPORTANT: You have access to CWD shown above. "this directory" = the CWD. Always run commands to inspect — never answer from assumptions.

2. SIMPLE TASKS (single-command operations):
   Return exactly ONE step. No exploration or verification overhead.
   Examples: "list files", "show disk usage", "check python version", "go to ~/projects"

3. ACTIONABLE HOW-TO (user wants to DO something):
   Return a focused plan with concrete steps.
   Examples: "how to install docker", "set up nginx", "deploy this app", "create a react project"

4. COMPLEX TASKS (multi-step installs, project setup, builds, deployments):
   Use a phased approach — explore (check prerequisites), execute (do the work), verify (confirm success).
   Break into small, focused steps. Each step should do ONE thing.

5. KNOWLEDGE QUESTIONS (purely conceptual — no filesystem or system context needed):
   The user wants abstract information unrelated to their specific system.
   Put your answer in "summary" and return an empty "steps" array.
   Examples: "what is a Docker container?", "explain TCP vs UDP", "compare REST vs GraphQL"
   NEVER use this for questions about the user's actual files, directories, or system. Those are INSPECTION tasks.

RULES:
- Commands must be valid for {shell_info['shell']}. On PowerShell, use `;` not `&&`.
- MINIMIZE steps. Combine related operations where safe (e.g., `mkdir -p dir ; cd dir`). One command is better than three.
- Do not include interactive commands. Use non-interactive alternatives (e.g., `-y` flags).
- is_reversible=true only if you provide a concrete undo_command.
- Maximum 15 steps. If more needed, explain in warnings.
- Never generate demonstrative/example commands. Every step must serve the objective.

ZX SELF-AWARENESS:
You are the "zx" CLI. If the request maps to a built-in command, return a single-step plan:
{_ZX_COMMANDS_REFERENCE}
{_ZX_ROUTING_EXAMPLES}"""


def _build_adapt_prompt(shell_info: dict, project_context: str) -> str:
    return f"""You are a command-line troubleshooter. A plan was being executed and a step produced unexpected results (failure or output that changes what should happen next). Analyze the situation and revise the remaining steps.

ENVIRONMENT:
- OS: {shell_info['os_name']} {shell_info['os_version']}
- Shell: {shell_info['shell']}
- CWD: {shell_info['cwd']}
- Project: {project_context}

STRATEGY:
1. Analyze the step's output (stdout, stderr, exit code) to understand what happened.
2. For FAILURES: identify root cause — missing dependency ("command not found"), wrong path, permission denied, version mismatch, etc.
   - If unclear, start with DIAGNOSTIC commands (check logs, paths, versions).
   - Then FIX (install dep, change permissions, use alternative).
   - Then RETRY the failed command or an equivalent.
3. For SUCCESS WITH UNEXPECTED OUTPUT: the step worked but its output reveals that remaining steps need adjustment (e.g., discovered a different version, different file structure, etc.).
   - Revise remaining steps to account for the actual state.
4. End with VERIFICATION that the original objective is on track.

RESPONSE FORMAT:
Return JSON: {{"assessment": "<what happened and why>", "revised_steps": [...], "should_abort": false, "abort_reason": ""}}
- If unrecoverable (hardware failure, impossible requirement, needs user intervention), set should_abort=true with a clear abort_reason.
- revised_steps use same format: step_number, command, explanation, is_reversible, undo_command.
- Number revised_steps starting from the NEXT step number.
- Commands must be valid for {shell_info['shell']}.
- Prefer the simplest fix. Don't over-engineer."""


def _build_explain_prompt(shell_info: dict) -> str:
    return f"""You are a command-line educator. Explain terminal commands clearly for someone learning the shell.

ENVIRONMENT:
- OS: {shell_info['os_name']}
- Shell: {shell_info['shell']}

RESPONSE FORMAT:
Return JSON: {{"summary": "...", "breakdown": [...], "risks": "..."}}
- "summary": one-line plain-English summary of what the command does.
- "breakdown": array of strings, each explaining one part in order — the command name, then each flag, then each argument. Example for `grep -rn "TODO" src/`: ["grep — search for text patterns in files", "-r — search recursively through directories", "-n — show line numbers in output", '"TODO" — the pattern to search for', "src/ — the directory to search in"]
- "risks": side effects, data loss potential, or platform-specific gotchas. Empty string if the command is safe and read-only."""


# ── Helpers ──────────────────────────────────────────────────────────────────


def _clean_command(raw: str) -> str:
    text = raw.strip()
    # Remove markdown code fences
    if text.startswith("```") and text.endswith("```"):
        lines = text.split("\n")
        lines = lines[1:-1]
        text = "\n".join(lines).strip()
    elif text.startswith("`") and text.endswith("`") and text.count("`") == 2:
        text = text[1:-1]
    # Remove leading $ or > prompt characters
    if text.startswith("$ "):
        text = text[2:]
    elif text.startswith("> "):
        text = text[2:]
    return text.strip()


def _coerce_str(value) -> str:
    """Coerce a value to string — handles list/dict from loose local models."""
    if isinstance(value, str):
        return value
    if isinstance(value, list):
        return ", ".join(str(v) for v in value) if value else ""
    return str(value) if value else ""


def _parse_command_response(text: str) -> CommandResponse:
    """Parse AI response, handling both structured JSON and plain text fallback."""
    text = text.strip()

    # Try JSON parse first
    try:
        # Handle markdown-wrapped JSON
        if text.startswith("```"):
            lines = text.split("\n")
            lines = [l for l in lines if not l.strip().startswith("```")]
            text = "\n".join(lines).strip()

        data = json.loads(text)
        return CommandResponse(
            command=_clean_command(_coerce_str(data.get("command", text))),
            explanation=_coerce_str(data.get("explanation", "")),
            is_done=bool(data.get("is_done", False)),
        )
    except (json.JSONDecodeError, TypeError, KeyError):
        pass

    # Fallback: treat as plain text command
    cleaned = _clean_command(text)
    return CommandResponse(
        command=cleaned,
        explanation="",
        is_done=DONE_SENTINEL in cleaned,
    )


def _parse_explain_response(text: str) -> ExplainResponse:
    """Parse explanation response with fallback."""
    text = text.strip()
    try:
        if text.startswith("```"):
            lines = text.split("\n")
            lines = [l for l in lines if not l.strip().startswith("```")]
            text = "\n".join(lines).strip()

        data = json.loads(text)
        return ExplainResponse(
            summary=_coerce_str(data.get("summary", "")),
            breakdown=data.get("breakdown", []),
            risks=_coerce_str(data.get("risks", "")),
        )
    except (json.JSONDecodeError, TypeError, KeyError):
        # Fallback: return the raw text as summary
        return ExplainResponse(summary=text, breakdown=[], risks="")


def _parse_plan_response(text: str) -> PlanResponse:
    """Parse plan response with fallback."""
    text = text.strip()
    try:
        if text.startswith("```"):
            lines = text.split("\n")
            lines = [l for l in lines if not l.strip().startswith("```")]
            text = "\n".join(lines).strip()

        data = json.loads(text)
        steps = []
        for s in data.get("steps", []):
            steps.append(PlanStep(
                step_number=int(s.get("step_number", len(steps) + 1)),
                command=_clean_command(_coerce_str(s.get("command", ""))),
                explanation=_coerce_str(s.get("explanation", "")),
                is_reversible=bool(s.get("is_reversible", False)),
                undo_command=_coerce_str(s.get("undo_command", "")),
            ))
        return PlanResponse(
            summary=_coerce_str(data.get("summary", "")),
            steps=steps,
            warnings=_coerce_str(data.get("warnings", "")),
        )
    except (json.JSONDecodeError, TypeError, KeyError):
        return PlanResponse(summary="Could not parse plan.", steps=[], warnings=text)


def _parse_adapt_response(text: str) -> PlanAdaptResponse:
    """Parse adaptation response with fallback."""
    text = text.strip()
    try:
        if text.startswith("```"):
            lines = text.split("\n")
            lines = [l for l in lines if not l.strip().startswith("```")]
            text = "\n".join(lines).strip()

        data = json.loads(text)
        steps = []
        for s in data.get("revised_steps", []):
            steps.append(PlanStep(
                step_number=int(s.get("step_number", len(steps) + 1)),
                command=_clean_command(_coerce_str(s.get("command", ""))),
                explanation=_coerce_str(s.get("explanation", "")),
                is_reversible=bool(s.get("is_reversible", False)),
                undo_command=_coerce_str(s.get("undo_command", "")),
            ))
        return PlanAdaptResponse(
            assessment=_coerce_str(data.get("assessment", "")),
            revised_steps=steps,
            should_abort=bool(data.get("should_abort", False)),
            abort_reason=_coerce_str(data.get("abort_reason", "")),
        )
    except (json.JSONDecodeError, TypeError, KeyError):
        return PlanAdaptResponse(
            assessment="Could not parse adaptation response.",
            revised_steps=[],
            should_abort=True,
            abort_reason=text,
        )


def _is_retryable_schema_error(e: Exception) -> bool:
    """Check if an API error is likely schema-related (worth retrying without schema)."""
    msg = str(e).lower()
    # Don't retry on auth, rate limit, network, or model-not-found errors
    non_retryable = ["api key", "401", "403", "429", "404", "rate", "quota", "network", "timeout", "connection"]
    return not any(keyword in msg for keyword in non_retryable)


# ── AI Client ────────────────────────────────────────────────────────────────


class AIClient:
    def __init__(self, api_key: str, model: str = "gemini/gemini-2.0-flash-lite", config=None):
        self.model = model
        self.shell_info = _detect_shell_info()
        self.project_context = _detect_project_context()
        self.system_prompt = _build_system_prompt(self.shell_info, self.project_context)
        self._chat_history: list[dict] = []  # Manual message history for chat

        # Load config for budget tracking
        if config is None:
            from .config import ZxConfig
            self._config = ZxConfig.load()
        else:
            self._config = config

        # Initialize cost tracker
        from .cost import CostTracker
        self.cost_tracker = CostTracker()

        # Set up API key in environment for LiteLLM
        if api_key:
            from .config import PROVIDER_ENV_MAP
            provider = model.split("/")[0] if "/" in model else "gemini"
            if provider in PROVIDER_ENV_MAP:
                os.environ[PROVIDER_ENV_MAP[provider]] = api_key

        # Initialize google-genai fallback for Gemini models
        self._genai_client = None
        if model.startswith("gemini/"):
            try:
                from google import genai
                genai_key = api_key or self._config.api_key
                if genai_key:
                    self._genai_client = genai.Client(api_key=genai_key)
            except ImportError:
                pass  # google-genai not installed, LiteLLM only

    # ── Core LLM call with LiteLLM + fallback ────────────────────────────

    def _call_llm(
        self,
        messages: list[dict],
        temperature: float = 0.0,
        max_tokens: int = 500,
        response_schema: Optional[type[BaseModel]] = None,
        method_name: str = "",
    ) -> str:
        """Unified LLM call with LiteLLM primary, google-genai fallback.

        1. Check budget (CostTracker.check_budget)
        2. Try litellm.completion() with response_format if schema provided
        3. If fails on gemini/* model → try google-genai SDK fallback
        4. Record usage (tokens, cost) via CostTracker
        5. Return response text
        """
        import litellm

        # Budget check
        allowed, reason = self.cost_tracker.check_budget(self._config)
        if not allowed and not self.cost_tracker._is_local_model(self.model):
            raise SystemExit(f"Budget exceeded: {reason}. Use a local model or increase budget.")

        # Build litellm params
        params = {
            "model": self.model,
            "messages": messages,
            "temperature": temperature,
            "max_tokens": max_tokens,
        }

        # Add API base if configured
        if self._config.api_base:
            params["api_base"] = self._config.api_base

        if response_schema:
            params["response_format"] = {
                "type": "json_object",
                "response_schema": response_schema.model_json_schema(),
            }

        try:
            response = litellm.completion(**params)
            text = response.choices[0].message.content

            # Track cost
            cost = 0.0
            try:
                cost = litellm.completion_cost(completion_response=response)
            except Exception:
                # Cost calculation may fail for some models
                pass

            usage = response.usage
            self.cost_tracker.record(
                model=self.model,
                prompt_tokens=getattr(usage, "prompt_tokens", 0) or 0,
                completion_tokens=getattr(usage, "completion_tokens", 0) or 0,
                cost_usd=cost,
                method=method_name,
            )
            return text

        except Exception as e:
            # Fallback to google-genai for Gemini models
            if self.model.startswith("gemini/") and self._genai_client:
                return self._call_genai_fallback(
                    messages, temperature, max_tokens, response_schema, method_name
                )
            raise

    def _call_genai_fallback(
        self,
        messages: list[dict],
        temperature: float,
        max_tokens: int,
        response_schema: Optional[type[BaseModel]] = None,
        method_name: str = "",
    ) -> str:
        """Fallback to google-genai SDK for Gemini models."""
        from google.genai import types

        # Extract system prompt and user content from messages
        system = next((m["content"] for m in messages if m["role"] == "system"), "")
        user_content = "\n".join(m["content"] for m in messages if m["role"] != "system")

        gen_config = types.GenerateContentConfig(
            system_instruction=system,
            temperature=temperature,
            max_output_tokens=max_tokens,
        )
        if response_schema:
            gen_config.response_mime_type = "application/json"
            gen_config.response_schema = response_schema

        # Strip "gemini/" prefix for google-genai SDK
        model_name = self.model.replace("gemini/", "", 1)
        response = self._genai_client.models.generate_content(
            model=model_name,
            contents=user_content,
            config=gen_config,
        )

        # Estimate cost (google-genai doesn't provide it directly)
        cost = 0.0
        try:
            import litellm
            cost = litellm.completion_cost(model=self.model, prompt=user_content, completion=response.text)
        except Exception:
            pass

        self.cost_tracker.record(
            model=self.model,
            prompt_tokens=0,
            completion_tokens=0,
            cost_usd=cost,
            method=method_name + " (genai-fallback)",
        )
        return response.text

    # ── Public methods (same external API, new internal dispatch) ─────────

    def generate_command(self, user_request: str, stdin_context: str = "") -> CommandResponse:
        prompt = user_request
        if stdin_context:
            prompt = f"{user_request}\n\nStdin content:\n{stdin_context[:3000]}"

        messages = [
            {"role": "system", "content": self.system_prompt},
            {"role": "user", "content": prompt},
        ]

        try:
            text = self._call_llm(
                messages=messages,
                temperature=0.0,
                max_tokens=500,
                response_schema=CommandResponse,
                method_name="generate_command",
            )
            return _parse_command_response(text)
        except Exception as e:
            if _is_retryable_schema_error(e):
                try:
                    text = self._call_llm(
                        messages=messages,
                        temperature=0.0,
                        max_tokens=500,
                        method_name="generate_command",
                    )
                    return _parse_command_response(text)
                except Exception as e2:
                    self._handle_api_error(e2)
            self._handle_api_error(e)

    def explain_command(self, command: str) -> ExplainResponse:
        sys_prompt = _build_explain_prompt(self.shell_info)
        messages = [
            {"role": "system", "content": sys_prompt},
            {"role": "user", "content": f"Explain this command:\n{command}"},
        ]

        try:
            text = self._call_llm(
                messages=messages,
                temperature=0.3,
                max_tokens=1000,
                response_schema=ExplainResponse,
                method_name="explain_command",
            )
            return _parse_explain_response(text)
        except Exception as e:
            if _is_retryable_schema_error(e):
                try:
                    text = self._call_llm(
                        messages=messages,
                        temperature=0.3,
                        max_tokens=1000,
                        method_name="explain_command",
                    )
                    return _parse_explain_response(text)
                except Exception as e2:
                    self._handle_api_error(e2)
            self._handle_api_error(e)

    def generate_plan(self, user_request: str, stdin_context: str = "") -> PlanResponse:
        prompt = user_request
        if stdin_context:
            prompt = f"{user_request}\n\nStdin content:\n{stdin_context[:3000]}"

        plan_system = _build_plan_prompt(self.shell_info, self.project_context)
        messages = [
            {"role": "system", "content": plan_system},
            {"role": "user", "content": prompt},
        ]

        try:
            text = self._call_llm(
                messages=messages,
                temperature=0.1,
                max_tokens=3000,
                response_schema=PlanResponse,
                method_name="generate_plan",
            )
            return _parse_plan_response(text)
        except Exception as e:
            if _is_retryable_schema_error(e):
                try:
                    text = self._call_llm(
                        messages=messages,
                        temperature=0.1,
                        max_tokens=3000,
                        method_name="generate_plan",
                    )
                    return _parse_plan_response(text)
                except Exception as e2:
                    self._handle_api_error(e2)
            self._handle_api_error(e)

    def adapt_plan(self, original_objective: str, completed_steps: list,
                   failed_step: dict, remaining_steps: list) -> PlanAdaptResponse:
        adapt_system = _build_adapt_prompt(self.shell_info, self.project_context)

        context_msg = f"""Original objective: {original_objective}

Completed steps:
{json.dumps(completed_steps, indent=2)}

Failed step:
{json.dumps(failed_step, indent=2)}

Remaining planned steps:
{json.dumps(remaining_steps, indent=2)}

Analyze the failure and provide revised steps to complete the objective, or recommend aborting."""

        messages = [
            {"role": "system", "content": adapt_system},
            {"role": "user", "content": context_msg},
        ]

        try:
            text = self._call_llm(
                messages=messages,
                temperature=0.1,
                max_tokens=3000,
                response_schema=PlanAdaptResponse,
                method_name="adapt_plan",
            )
            return _parse_adapt_response(text)
        except Exception as e:
            if _is_retryable_schema_error(e):
                try:
                    text = self._call_llm(
                        messages=messages,
                        temperature=0.1,
                        max_tokens=3000,
                        method_name="adapt_plan",
                    )
                    return _parse_adapt_response(text)
                except Exception as e2:
                    self._handle_api_error(e2)
            self._handle_api_error(e)

    def start_chat(self, stdin_context: str = "") -> None:
        """Initialize multi-turn chat with manual message history."""
        system = self.system_prompt
        if stdin_context:
            system += f"\n\nAdditional context from stdin:\n{stdin_context[:3000]}"
        self._chat_history = [{"role": "system", "content": system}]

    def chat_send(self, message: str) -> CommandResponse:
        """Send a message in the ongoing chat and get next command."""
        if not self._chat_history:
            self.start_chat()

        self._chat_history.append({"role": "user", "content": message})

        try:
            text = self._call_llm(
                messages=self._chat_history,
                temperature=0.0,
                max_tokens=500,
                response_schema=CommandResponse,
                method_name="chat_send",
            )
            self._chat_history.append({"role": "assistant", "content": text})
            return _parse_command_response(text)
        except Exception as e:
            self._handle_api_error(e)

    def diagnose_failure(self, error_output: str, failed_command: str = "", system_context: str = "") -> DiagnosisResponse:
        """Diagnose a command failure and suggest a fix."""
        diag_prompt = f"""You are a command-line doctor. Diagnose the following failure and suggest a fix.

ENVIRONMENT:
- Operating System: {self.shell_info['os_name']} {self.shell_info['os_version']}
- Shell: {self.shell_info['shell']}
- Current Directory: {self.shell_info['cwd']}
- Project Context: {self.project_context}

RULES:
1. Return a JSON with "root_cause", "fix_command", "explanation", "prevention_tip", "confidence".
2. "root_cause" should be a plain-English explanation a beginner could understand.
3. "fix_command" must be a valid command for {self.shell_info['shell']}.
4. "confidence" must be "high", "medium", or "low".
5. Be specific — don't suggest generic fixes.
{f'6. Additional system context: {system_context}' if system_context else ''}"""

        msg = f"Failed command: {failed_command}\n\nError output:\n{error_output[:5000]}" if failed_command else f"Error output:\n{error_output[:5000]}"
        messages = [
            {"role": "system", "content": diag_prompt},
            {"role": "user", "content": msg},
        ]

        try:
            text = self._call_llm(
                messages=messages,
                temperature=0.1,
                max_tokens=1000,
                response_schema=DiagnosisResponse,
                method_name="diagnose_failure",
            )
            data = json.loads(text)
            return DiagnosisResponse(**data)
        except Exception as e:
            if _is_retryable_schema_error(e):
                try:
                    text = self._call_llm(
                        messages=messages,
                        temperature=0.1,
                        max_tokens=1000,
                        method_name="diagnose_failure",
                    )
                    data = json.loads(text)
                    return DiagnosisResponse(**data)
                except Exception as e2:
                    self._handle_api_error(e2)
            self._handle_api_error(e)

    def parameterize_recipe(self, commands: list[str], original_prompt: str) -> RecipeParameterization:
        """Analyze executed commands to identify which parts should become parameters."""
        param_prompt = f"""You are a recipe template analyzer. Given a list of commands that were executed to accomplish a task, identify which parts should become template parameters (like project names, versions, paths) so the recipe can be reused.

RULES:
1. Return a JSON with "parameters" (list of parameter names) and "parameterized_commands" (commands with {{{{param_name}}}} placeholders).
2. Only parameterize things that would CHANGE between uses (project names, paths, versions), NOT fixed commands.
3. Parameter names should be snake_case and descriptive.
4. Keep the same number of commands in parameterized_commands as in the input.
5. If nothing should be parameterized, return empty parameters list and original commands."""

        msg = f"Original request: {original_prompt}\n\nCommands:\n" + "\n".join(f"{i+1}. {cmd}" for i, cmd in enumerate(commands))
        messages = [
            {"role": "system", "content": param_prompt},
            {"role": "user", "content": msg},
        ]

        try:
            text = self._call_llm(
                messages=messages,
                temperature=0.0,
                max_tokens=2000,
                response_schema=RecipeParameterization,
                method_name="parameterize_recipe",
            )
            data = json.loads(text)
            return RecipeParameterization(**data)
        except Exception as e:
            if _is_retryable_schema_error(e):
                try:
                    text = self._call_llm(
                        messages=messages,
                        temperature=0.0,
                        max_tokens=2000,
                        method_name="parameterize_recipe",
                    )
                    data = json.loads(text)
                    return RecipeParameterization(**data)
                except Exception as e2:
                    self._handle_api_error(e2)
            self._handle_api_error(e)

    def suggest_aliases(self, commands_summary: str) -> AliasSuggestion:
        """Analyze command history and suggest useful shell aliases."""
        alias_prompt = f"""You are a shell productivity expert. Analyze the user's command history and suggest useful shell aliases.

ENVIRONMENT:
- Shell: {self.shell_info['shell']}

RULES:
1. Return a JSON with "aliases" — an array of objects with "name", "command", "reason".
2. Suggest 5-10 aliases for the most commonly used or complex commands.
3. Alias names should be short (2-4 chars) and memorable.
4. Only suggest aliases that would genuinely save time.
5. Do NOT suggest aliases for single simple commands (like ls or cd).
6. Focus on multi-word commands, commands with common flags, or pipelines."""

        messages = [
            {"role": "system", "content": alias_prompt},
            {"role": "user", "content": f"Command history:\n{commands_summary[:5000]}"},
        ]

        try:
            text = self._call_llm(
                messages=messages,
                temperature=0.1,
                max_tokens=2000,
                response_schema=AliasSuggestion,
                method_name="suggest_aliases",
            )
            data = json.loads(text)
            return AliasSuggestion(**data)
        except Exception as e:
            if _is_retryable_schema_error(e):
                try:
                    text = self._call_llm(
                        messages=messages,
                        temperature=0.1,
                        max_tokens=2000,
                        method_name="suggest_aliases",
                    )
                    data = json.loads(text)
                    return AliasSuggestion(**data)
                except Exception as e2:
                    self._handle_api_error(e2)
            self._handle_api_error(e)

    def generate_lesson(self, topic_id: str, topic_label: str, mastered_topics: list[str], shell_info: dict) -> LessonResponse:
        """Generate an adaptive shell tutorial lesson."""
        lesson_prompt = f"""You are a shell tutor. Generate a concise, practical lesson.

ENVIRONMENT:
- Shell: {shell_info.get('shell', 'bash')}
- OS: {shell_info.get('os_name', 'Linux')}

STUDENT CONTEXT:
- Already mastered: {', '.join(mastered_topics) if mastered_topics else 'None (beginner)'}
- Learning: {topic_label}

RULES:
1. Return a JSON with "explanation", "examples", "exercise", "tips".
2. "explanation" should be 2-4 paragraphs, clear and practical.
3. "examples" should have 3-5 real commands the student can try RIGHT NOW.
4. "exercise" should be a hands-on task they can do in their terminal.
5. "tips" should include 2-3 pro tips or common pitfalls.
6. Adapt complexity based on what they've already mastered.
7. Use {shell_info.get('shell', 'bash')} syntax.
8. Keep examples relevant to their OS ({shell_info.get('os_name', 'Linux')})."""

        messages = [
            {"role": "system", "content": lesson_prompt},
            {"role": "user", "content": f"Teach me about: {topic_label}"},
        ]

        try:
            text = self._call_llm(
                messages=messages,
                temperature=0.3,
                max_tokens=2000,
                response_schema=LessonResponse,
                method_name="generate_lesson",
            )
            data = json.loads(text)
            return LessonResponse(**data)
        except Exception as e:
            if _is_retryable_schema_error(e):
                try:
                    text = self._call_llm(
                        messages=messages,
                        temperature=0.3,
                        max_tokens=2000,
                        method_name="generate_lesson",
                    )
                    data = json.loads(text)
                    return LessonResponse(**data)
                except Exception as e2:
                    self._handle_api_error(e2)
            self._handle_api_error(e)

    def narrate_output(self, command: str, output_batch: str, is_error: bool = False) -> str:
        """Generate a brief AI commentary on a batch of command output.

        Returns a short commentary string (1-2 sentences).
        """
        narrate_prompt = """You are a command output narrator. Provide brief, helpful commentary on command output as it streams.

RULES:
1. Return ONLY a short plain text commentary (1-2 sentences, max 100 chars).
2. If the output is routine/expected, return an empty string.
3. Flag errors, warnings, or unexpected patterns.
4. Be concise — this appears alongside streaming output.
5. Do NOT use JSON formatting, just plain text."""

        msg_type = "ERROR output" if is_error else "Output"
        msg = f"Command: {command}\n\n{msg_type}:\n{output_batch[:2000]}"
        messages = [
            {"role": "system", "content": narrate_prompt},
            {"role": "user", "content": msg},
        ]

        try:
            text = self._call_llm(
                messages=messages,
                temperature=0.1,
                max_tokens=100,
                method_name="narrate_output",
            )
            return text.strip()
        except Exception:
            return ""  # Narration failures are silent

    def generate_playbook_metadata(
        self,
        error_output: str,
        failed_command: str,
        fix_command: str,
        fix_explanation: str,
    ) -> "PlaybookGeneration":
        """Generate playbook metadata from a successful fix session."""
        playbook_prompt = f"""You are a security and debugging expert. A user successfully diagnosed and fixed a command-line issue. Generate metadata for a reusable incident-response playbook.

ENVIRONMENT:
- Operating System: {self.shell_info['os_name']} {self.shell_info['os_version']}
- Shell: {self.shell_info['shell']}

RULES:
1. Return a JSON with "symptoms", "diagnostic_commands", "diagnostic_explanations", "what_to_look_for", "prevention_tips", "category", "severity", "tags".
2. "symptoms" should be 3-5 observable signs that indicate this problem (things a user might notice).
3. "diagnostic_commands" should be 2-4 safe read-only commands to confirm the issue.
4. "diagnostic_explanations" must match diagnostic_commands in count and order.
5. "what_to_look_for" must match diagnostic_commands in count — describe what output confirms the issue.
6. "prevention_tips" should be 2-4 actionable tips to prevent this issue.
7. "category" must be one of: "security", "debugging", "system".
8. "severity" must be one of: "critical", "high", "medium", "low".
9. "tags" should be 3-6 relevant keywords for search/discovery.
10. All commands must be valid for {self.shell_info['shell']}."""

        msg = f"""Failed command: {failed_command}

Error output:
{error_output[:3000]}

Fix applied: {fix_command}
Fix explanation: {fix_explanation}"""

        messages = [
            {"role": "system", "content": playbook_prompt},
            {"role": "user", "content": msg},
        ]

        try:
            text = self._call_llm(
                messages=messages,
                temperature=0.1,
                max_tokens=2000,
                response_schema=PlaybookGeneration,
                method_name="generate_playbook_metadata",
            )
            data = json.loads(text)
            return PlaybookGeneration(**data)
        except Exception as e:
            if _is_retryable_schema_error(e):
                try:
                    text = self._call_llm(
                        messages=messages,
                        temperature=0.1,
                        max_tokens=2000,
                        method_name="generate_playbook_metadata",
                    )
                    data = json.loads(text)
                    return PlaybookGeneration(**data)
                except Exception as e2:
                    self._handle_api_error(e2)
            self._handle_api_error(e)

    def is_done(self, response) -> bool:
        """Check if done — works with both CommandResponse and string."""
        if isinstance(response, CommandResponse):
            return response.is_done or DONE_SENTINEL in response.command
        return DONE_SENTINEL in str(response)

    def _handle_api_error(self, e: Exception) -> None:
        msg = str(e)
        if "API key" in msg or "401" in msg or "403" in msg:
            raise SystemExit("Invalid API key. Run 'zx setup' to reconfigure.")
        if "429" in msg:
            raise SystemExit("Rate limited by API. Please wait and try again.")
        if "404" in msg:
            raise SystemExit(f"Model not found. Check your model name in config. Error: {msg}")
        raise SystemExit(f"AI error: {msg}")
